// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDozYrIlN7G93A7eCbn9tqIaFmriim0Kao',
    appId: '1:589488084049:web:04110a8deffa4310e71470',
    messagingSenderId: '589488084049',
    projectId: 'social-media-98207',
    authDomain: 'social-media-98207.firebaseapp.com',
    storageBucket: 'social-media-98207.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpwUVlaNPII165WxVeOr2f-8ShiTSJMCI',
    appId: '1:589488084049:android:27e0f9e7967c4f96e71470',
    messagingSenderId: '589488084049',
    projectId: 'social-media-98207',
    storageBucket: 'social-media-98207.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByiveUMxWI9EK5BZMtOYEludL7HKB7e1g',
    appId: '1:589488084049:ios:d4b16cdd029a4149e71470',
    messagingSenderId: '589488084049',
    projectId: 'social-media-98207',
    storageBucket: 'social-media-98207.firebasestorage.app',
    iosBundleId: 'com.example.socialmedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByiveUMxWI9EK5BZMtOYEludL7HKB7e1g',
    appId: '1:589488084049:ios:d4b16cdd029a4149e71470',
    messagingSenderId: '589488084049',
    projectId: 'social-media-98207',
    storageBucket: 'social-media-98207.firebasestorage.app',
    iosBundleId: 'com.example.socialmedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDozYrIlN7G93A7eCbn9tqIaFmriim0Kao',
    appId: '1:589488084049:web:62b484a5dc79a6e8e71470',
    messagingSenderId: '589488084049',
    projectId: 'social-media-98207',
    authDomain: 'social-media-98207.firebaseapp.com',
    storageBucket: 'social-media-98207.firebasestorage.app',
  );
}
